### ISSUE TITLE
O365 remove multiple licenses at same time

### ISSUE THREAD

**Issue by KP-GIT** [Scine/Office365#2]
Hi Scine,

Need your help, hope you don't mind me raising an issue.

I am working on a script which removes the licenses of an office365 user.

In the script I need to remove multiple irrelevant licenses of an user. Now all these irrelevant licenses would be received dynamically and will be stored in a variable.

I know if we had known the name of the licenses to be removed beforehand. This will be the command : 

`Set-MsolUserLicense -UserPrincipalName "TestB@lic.com" -RemoveLicenses "liconline:DESKLESSPACK","liconline:OFFICESUBSCRIPTION";`

Assuming F1 and proplus are the licenses not required by the user TestB. I ran this and it produced the expected results.

However that is not going to work in our case as we will need to do that dynamically(we might not know what are those and how many of those licenses)

So I tried it running this way : 

```
$license = "`"liconline:DESKLESSPACK`",`"liconline:OFFICESUBSCRIPTION`""
Set-MsolUserLicense -UserPrincipalName "TestB@lic.com" -RemoveLicenses $license;
```

But it gave following error : 

> Set-MsolUserLicense : Unable to assign this license because it is invalid. Use the Get-MsolAccountSku cmdlet to retrieve a list of valid licenses.

I don't know what is wrong here since both of the licenses needs to be under double quotes I have provided the same in the string and escaped it using a back tick

Would you be by any chance spare some time and help me out with this. I couldn't think of any other way to fix this and I don't want to split the string and iterate it maybe through a for loop.

**Comment by Scine** [comment]
Hi Karan,

 

Absolutely.  I think your problem lies here:

 

Set-MsolUserLicense : Unable to assign this license because it is invalid. Use the Get-MsolAccountSku cmdlet to retrieve a list of valid licenses.

 

 

Run get-msolaccountsku and it’ll give you the list of licenses that you have in your tenant account.  Then check to see if that’s in your list of licenses you’re trying to remove, and also check for typos in your script perhaps?

 

That’d be my first guess.  But feel free to ask any other questions you have!

**Comment by KP-GIT** [comment]
Thanks A Lot Man!!!
I am relieved knowing someone having an idea of this thing is with me :)

I understand where you are coming from, but that is the thing these two licenses are very much correct without any typo. 

when I am trying to remove it in this way

`Set-MsolUserLicense -UserPrincipalName "TestB@lic.com" -RemoveLicenses "liconline:DESKLESSPACK","liconline:OFFICESUBSCRIPTION";`

it definitely works

But if I grab them in a variable

```
$license = "`"liconline:DESKLESSPACK`",`"liconline:OFFICESUBSCRIPTION`""
Set-MsolUserLicense -UserPrincipalName "TestB@lic.com" -RemoveLicenses $license;
```

It doesn't . I ensure the licenses are correct and there isn't any spelling mistake.

I hope I was able to explain. I am not good at explaining things.

Make sure you notice that the name of the licenses in the double quotes, now why I am doing that because  microsoft says so : 

https://docs.microsoft.com/en-us/office365/enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell

**Comment by KP-GIT** [comment]
Hey Travis,

I have figured it out, seems Sheldon was right ignorance can never be bliss :p

Someone helped me with this : 

https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoluserlicense?view=azureadps-1.0#parameters

Which says the -RemoveLicenses switch expects a **String array** and not just a plain String. The other post of microsoft mentioned the licenses to be removed have to be provided this way 

> -RemoveLicenses "license A","license B","license C"

and I mistook it as a string which was wrong.

So this is what will work

```
$license="licentonline:DESKLESSPACK","licentonline:OFFICESUBSCRIPTION"
#powershell will automatically convert above string to an array
Set-MsolUserLicense -UserPrincipalName "ID_TestB@licent.com" -RemoveLicenses $license;
```

Hence closing this issue, sorry for troubling you for such a minor issue and thanks for all your help

**Comment by Scine** [comment]
No trouble at all!  Glad you got it figured out!  Have a good day!

**Comment by Kenthesystrainee** [comment]
So, why am i in this convo?😂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Scine** [comment]
I guess because you’re just that awesome?  Not a clue. :).

**Comment by Kenthesystrainee** [comment]
Well i work as a sysadmin and in network installation/management

But not too good at code

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Scine** [comment]
That’s ok, we all started somewhere. 😊  I’m awful at higher end networking. 😊

**Comment by Kenthesystrainee** [comment]
Haha yeah! just finished the apprenticeship, moving into a full time job 😁 and this is definetly the most random conversation i’ve had on some random email ticket from a company based where?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Scine** [comment]
Portland Oregon.  :)

**Comment by Absoblogginlutely** [comment]
> So, why am i in this convo?😂 Get Outlook for iOS<https://aka.ms/o0ukef>

It looks like you starred the project in Github but that (in theory) doesn't mean you should be getting bug notices based on my reading of the starring project notes. At least random conversations are better than getting hundreds of autoreplies to a thread because someone has left the company and still subscribed to post notifications. That was fun to wake up to this morning!

**Comment by Kenthesystrainee** [comment]
Oh wait, it’s hesby😂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
